version: '3.9'
services:
    rest-server:
        container_name: rest-server
        build:
            dockerfile: Dockerfile
        ports:
            - $SPRING_DOCKER_PORT:$SPRING_DOCKER_PORT
        networks:
            - spring-network
        depends_on:
            - mariadb
        restart: on-failure
        env_file: ./.env
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url"  : "jdbc:mariadb://$DB_HOST:3306/$DB_NAME?useSSL=false",
                "spring.datasource.username" : "$DB_USER",
                "spring.datasource.password" : "$DB_PASSWORD",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDB10Dialect",
                "spring.jpa.hibernate.ddl-auto" : "update",
                "saverioriotto.app.jwtSecret" : "sRSecretKey",
                "saverioriotto.app.jwtExpirationMs" : "86400000",
                "server.port" : "$SPRING_DOCKER_PORT"}'
    mariadb:
      image: mariadb:10.2
      container_name: mariadb
      env_file: ./.env
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      volumes:
      - mariadb:/var/lib/mysql
      networks:
        - spring-network
      restart: on-failure
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpma
        links:
        - mariadb:mariadb
        ports:
        - 80:80
        environment:
          PMA_HOST: mariadb
          PMA_PORT: 3306
        networks:
          - spring-network 
        
networks:
    spring-network:
        driver: bridge

volumes:
    mariadb:
        driver: local